name: Lint & Test

on:
  push:

  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:
  lint:
    name: Lint & Test
    runs-on: ubuntu-latest
    env:
      PIP_NO_CACHE_DIR: false
      PIP_USER: 1

      POETRY_VIRTUALENVS_CREATE: false

      PYTHONUSERBASE: ${{ github.workspace }}/.cache/py-user-base
      PRE_COMMIT_HOME: ${{ github.workspace }}/.cache/pre-commit-cache

    steps:
    - name: Add PYTHONUSERBASE to PATH
      run: echo '${{ env.PYTHONUSERBASE }}/bin/' >> $GITHUB_PATH

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9
        architecture: x64

    - name: Cache Pip Folder
      uses: actions/cache@v2
      id: pip-cache
      with:
        path: ${{ env.PYTHONUSERBASE }}
        key: pip-${{ runner.os }}-${{ hashFiles('pyproject.toml', 'poetry.lock') }}

    - name: Install Depedencies
      if: steps.pip-cache.outputs.cache-hit != 'true'
      run: |
        pip install poetry
        poetry install

    - name: Cache Pre-Commit Environments
      uses: actions/cache@v2
      with:
        path: ${{ env.PRE_COMMIT_HOME }}
        key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Run Linting
      env:
        PIP_USER: 0
      run: pre-commit run --all-files

    - name: Run Tests
      env:
        PIP_USER: 0
      run: pytest -v
